# SLF4J SimpleLogger configuration
# This file configures the SimpleLogger implementation of SLF4J.
# Levels: OFF < ERROR < WARN < INFO < DEBUG < TRACE

# Root default level for all loggers
org.slf4j.simpleLogger.defaultLogLevel=INFO

# Specific logger levels can be set here to override default
org.slf4j.simpleLogger.log.org.eclipse.jetty=WARN
org.slf4j.simpleLogger.log.org.eclipse.jetty.server=WARN
org.slf4j.simpleLogger.log.org.eclipse.jetty.util=WARN
org.slf4j.simpleLogger.log.org.http4k=WARN
org.slf4j.simpleLogger.log.org.apache.commons.dbutils=WARN
org.slf4j.simpleLogger.log.software.amazon.awssdk=WARN
org.slf4j.simpleLogger.log.com.azure.cognitos=WARN
org.slf4j.simpleLogger.log.com.azure.cosmos=WARN
org.slf4j.simpleLogger.log.com.fasterxml.jackson=WARN
org.slf4j.simpleLogger.log.org.slf4j=WARN

# Internal application logs we may want to see at INFO (co.onmind)
org.slf4j.simpleLogger.log.co.onmind=INFO
